### ISSUE TITLE
Processing 3

### ISSUE THREAD

**Issue by ilianvlm** [jberberick/pde-runtime-editor#2]
I know it's been a long time but I find your runtime editor to be extremely useful in development and in teaching so I was wondering if you had an update for Processing3

When I try to run new RuntimeEditor(this,true) I get "VerifyError: Bad type on operand stackException Details: Location: runtimeeditor/RuntimeEditor.addControlFrame(Ljava/lang/String;llllLruntimeedtor/RuntimeEditor$ControlFrame; @33; invokevirtual

I am not sure if this a incompatibility with ControlP5 or Processing3

**Comment by jberberick** [comment]
I updated the Runtime Editor to work with Processing 3.x, but tooltips do not work yet.  The zip can be downloaded from the [Release tab](https://github.com/jberberick/pde-runtime-editor/releases/tag/v1.1).

I'd like to see what projects the Runtime Editor helped with.  Please post them on the library's processing forum [thread](https://forum.processing.org/two/discussion/16711/processing-runtime-editor-modify-variables-live).

**Comment by ilianvlm** [comment]
Will do! Thank you very much.
